//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int Id { get; set; }
        public int Biller_ID { get; set; }
        public int Branch_ID { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Contact { get; set; }
        public int Amount { get; set; }
        public System.DateTime Date { get; set; }
        public string Payment_Mode { get; set; }
    
        public virtual Biller Biller { get; set; }
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
