//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Id { get; set; }
        public int Stock_ID { get; set; }
        public int Bill_ID { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Total { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
