//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSMSAdmin.ServiceAdmin {
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admindata", Namespace="http://schemas.datacontract.org/2004/07/BSMS.AdminService")]
    [System.SerializableAttribute()]
    public partial class Admindata : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://schemas.datacontract.org/2004/07/BSMS")]
    [System.SerializableAttribute()]
    public partial class Admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAdmin.IAdminService")]
    public interface IAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/selectAdmin", ReplyAction="http://tempuri.org/IAdminService/selectAdminResponse")]
        BSMSAdmin.ServiceAdmin.Admindata[] selectAdmin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/selectAdmin", ReplyAction="http://tempuri.org/IAdminService/selectAdminResponse")]
        System.Threading.Tasks.Task<BSMSAdmin.ServiceAdmin.Admindata[]> selectAdminAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/getSingle", ReplyAction="http://tempuri.org/IAdminService/getSingleResponse")]
        BSMSAdmin.ServiceAdmin.Admindata getSingle(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/getSingle", ReplyAction="http://tempuri.org/IAdminService/getSingleResponse")]
        System.Threading.Tasks.Task<BSMSAdmin.ServiceAdmin.Admindata> getSingleAsync(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/addAdmin", ReplyAction="http://tempuri.org/IAdminService/addAdminResponse")]
        BSMSAdmin.ServiceAdmin.Admin addAdmin(BSMSAdmin.ServiceAdmin.Admin a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/addAdmin", ReplyAction="http://tempuri.org/IAdminService/addAdminResponse")]
        System.Threading.Tasks.Task<BSMSAdmin.ServiceAdmin.Admin> addAdminAsync(BSMSAdmin.ServiceAdmin.Admin a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/updateAdmin", ReplyAction="http://tempuri.org/IAdminService/updateAdminResponse")]
        BSMSAdmin.ServiceAdmin.Admindata updateAdmin(BSMSAdmin.ServiceAdmin.Admin a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/updateAdmin", ReplyAction="http://tempuri.org/IAdminService/updateAdminResponse")]
        System.Threading.Tasks.Task<BSMSAdmin.ServiceAdmin.Admindata> updateAdminAsync(BSMSAdmin.ServiceAdmin.Admin a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/deleteAdmin", ReplyAction="http://tempuri.org/IAdminService/deleteAdminResponse")]
        BSMSAdmin.ServiceAdmin.Admin deleteAdmin(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/deleteAdmin", ReplyAction="http://tempuri.org/IAdminService/deleteAdminResponse")]
        System.Threading.Tasks.Task<BSMSAdmin.ServiceAdmin.Admin> deleteAdminAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceChannel : BSMSAdmin.ServiceAdmin.IAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<BSMSAdmin.ServiceAdmin.IAdminService>, BSMSAdmin.ServiceAdmin.IAdminService {
        
        public AdminServiceClient() {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BSMSAdmin.ServiceAdmin.Admindata[] selectAdmin() {
            return base.Channel.selectAdmin();
        }
        
        public System.Threading.Tasks.Task<BSMSAdmin.ServiceAdmin.Admindata[]> selectAdminAsync() {
            return base.Channel.selectAdminAsync();
        }
        
        public BSMSAdmin.ServiceAdmin.Admindata getSingle(int i) {
            return base.Channel.getSingle(i);
        }
        
        public System.Threading.Tasks.Task<BSMSAdmin.ServiceAdmin.Admindata> getSingleAsync(int i) {
            return base.Channel.getSingleAsync(i);
        }
        
        public BSMSAdmin.ServiceAdmin.Admin addAdmin(BSMSAdmin.ServiceAdmin.Admin a) {
            return base.Channel.addAdmin(a);
        }
        
        public System.Threading.Tasks.Task<BSMSAdmin.ServiceAdmin.Admin> addAdminAsync(BSMSAdmin.ServiceAdmin.Admin a) {
            return base.Channel.addAdminAsync(a);
        }
        
        public BSMSAdmin.ServiceAdmin.Admindata updateAdmin(BSMSAdmin.ServiceAdmin.Admin a) {
            return base.Channel.updateAdmin(a);
        }
        
        public System.Threading.Tasks.Task<BSMSAdmin.ServiceAdmin.Admindata> updateAdminAsync(BSMSAdmin.ServiceAdmin.Admin a) {
            return base.Channel.updateAdminAsync(a);
        }
        
        public BSMSAdmin.ServiceAdmin.Admin deleteAdmin(int id) {
            return base.Channel.deleteAdmin(id);
        }
        
        public System.Threading.Tasks.Task<BSMSAdmin.ServiceAdmin.Admin> deleteAdminAsync(int id) {
            return base.Channel.deleteAdminAsync(id);
        }

        public static implicit operator List<object>(AdminServiceClient v)
        {
            throw new NotImplementedException();
        }
    }
}
